apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "zookeeper.fullname" . }}
spec:
  serviceName: {{ include "zookeeper.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "zookeeper.name" . }}

  template:
    metadata:
      labels:
        app: {{ include "zookeeper.name" . }}
    spec:
      containers:
        - name: zookeeper
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: client
              containerPort: 2181
            - name: quorum
              containerPort: 2888
            - name: leader-election
              containerPort: 3888

          volumeMounts:
            - name: data
              mountPath: /data
            - name: datalog
              mountPath: /datalog
            - name: config
              mountPath: /conf/zoo.cfg
              subPath: zoo.cfg

      volumes:
        - name: config
          configMap:
            name: {{ include "zookeeper.fullname" . }}-config

  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage.size }}

    - metadata:
        name: datalog
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.storage.size }}

