version: "3.9"

services:
  solr:
    container_name: solr
    build: .
    ports:
      - "8983:8983"
    volumes:
      - solrdata:/var/solr/data
      - solrbackups:/var/solr/backups
    healthcheck:
      test: ["CMD", "/scripts/healthcheck.sh"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  solrdata:
  solrbackups:
