apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}-headless
spec:
  clusterIP: None
  selector:
    app: {{ include "kafka.name" . }}
  ports:
    - name: kafka
      port: 9092

