apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "kafka.name" . }}
  ports:
    - name: kafka
      port: 9092
      targetPort: kafka

