apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.fullname" . }}-headless
spec:
  clusterIP: None
  selector:
    app: {{ include "solr.name" . }}
  ports:
    - name: http
      port: 8983

