apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "solr.fullname" . }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: solr.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "solr.fullname" . }}
                port:
                  number: 8983

