apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: solrkafka-solr
  ports:
    - name: http
      port: 8983
      targetPort: http
      protocol: TCP

