apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.fullnameOverride | default (include "solr.fullname" .) }}
  labels:
    app: {{ .Values.fullnameOverride | default (include "solr.fullname" .) }}
spec:
  serviceName: {{ .Values.fullnameOverride | default (include "solr.fullname" .) }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.fullnameOverride | default (include "solr.fullname" .) }}
  template:
    metadata:
      labels:
        app: {{ .Values.fullnameOverride | default (include "solr.fullname" .) }}
    spec:
      serviceAccountName: {{ include "solr.serviceAccountName" . }}

      initContainers:
        - name: init-solr-data
          image: busybox
          securityContext:
            runAsUser: 0
            runAsGroup: 0
            allowPrivilegeEscalation: true
          command: ["sh", "-c", "mkdir -p /var/solr/data && chown -R 8983:8983 /var/solr/data"]
          volumeMounts:
            - name: solr-data
              mountPath: /var/solr/data

      containers:
        - name: solr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: 8983

          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: SOLR_HOST
              value: "$(POD_NAME).{{ .Values.fullnameOverride | default (include "solr.fullname" .) }}-headless.{{ .Release.Namespace }}.svc.cluster.local"

            - name: ZK_HOST
              value: "{{ .Values.zookeeper.hosts }}"

            - name: SOLR_HEAP
              value: "512m"

            - name: SOLR_HOME
              value: "/var/solr/data"

          command: ["bash", "-c"]
          args:
            - >
              cp /opt/solr/server/resources/log4j2.xml /var/solr/log4j2.xml &&
              /opt/solr/bin/solr start -cloud -f -z $ZK_HOST -host $SOLR_HOST -Dsolr.node.name=$POD_NAME

          volumeMounts:
            - name: solr-data
              mountPath: /var/solr/data

  volumeClaimTemplates:
    - metadata:
        name: solr-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.storage.size }}

