enabled: true

fullnameOverride: solrkafka-solr
nameOverride: solrkafka-solr

replicaCount: 3

storage:
  size: 10Gi

image:
  repository: solr
  pullPolicy: IfNotPresent
  tag: "9.4"

imagePullSecrets: []

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8983

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: solr.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

httpRoute:
  enabled: false
  annotations: {}
  parentRefs:
    - name: gateway
      sectionName: http
  hostnames:
    - solr.local
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /

resources: {}

livenessProbe:
  httpGet:
    path: /solr/admin/info/system
    port: http

readinessProbe:
  httpGet:
    path: /solr/admin/info/system
    port: http

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

volumes: []
volumeMounts: []

nodeSelector: {}
tolerations: []
affinity: {}

zookeeper:
  hosts: "solrkafka-zookeeper-headless:2181"

solrCloud:
  enabled: true
  zkHost: "solrkafka-zookeeper-headless:2181"

monthlyCollections:
  enabled: true
  schedule: "0 0 1 * *"

collections:
  shards: 2
  replicas: 3
  name: "meinecollection"

